

name: voila-environment
channels:
  - conda-forge
dependencies:
  - python==3.9.4
  - pip==22.1.1
  - jupyterlab==3.4.4
  - pip:
    - git+https://git.example.com/MyProject.git@5190366bc52ba5d8cc7a566e057691b324aa1770
    - aepsych-client==0.1.1
    - voila==0.3.6
    - ipywidgets==7.6.5



# dependencies:
#   - python==3.9.4
#   - pip==22.1.1
#   - pip:
#     - aepsych==0.2.0
#     - aepsych-client==0.1.1
#     - bqplot
#     - ipympl
#     - ipyvolume
#     - scipy
#     - voila
#     - ipywidgets==8
